<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>5&nbsp; Clinical Research with Survival Outcomes – Causal Inference in Clinical Medical Research</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../chapters/06-meta-analysis.html" rel="next">
<link href="../chapters/04-protocol-consent.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-d435cb5de042bf45aa1f575c7853b776.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar docked quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/05-survival.html"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Clinical Research with Survival Outcomes</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Causal Inference in Clinical Medical Research</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/01-framework.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Framework for Causal Inference</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/02-rct.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Randomized Controlled Trials</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/03-rct-statistics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Statistical Considerations in Randomized Controlled Trials</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/04-protocol-consent.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Writing Randomized Controlled Trial Protocols and Informed Consent</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/05-survival.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Clinical Research with Survival Outcomes</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/06-meta-analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Principles and Methods of Meta-analysis</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/07-advanced-meta.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Advanced Meta-analysis</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/08-dag-scm.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Causal Graphs and Structural Causal Models</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/09-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/10-propensity-score.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Causal Inference Methods Based on Propensity Scores</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/11-instrumental-variables.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Instrumental-Variable Methods</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/12-regression-discontinuity.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Regression Discontinuity</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/13-time-series.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Interrupted Time-Series Analysis</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/14-sensitivity-analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Sensitivity Analysis for Observational Research</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/15-mediation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Causal Mediation Analysis</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/16-repeated-measures.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Statistical Analysis of Repeated-Measures Data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/17-missing-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Missing Data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/18-ml-causal-inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Integrating Causal Inference and Machine Learning</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/19-heterogeneity.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Heterogeneity and Individual Causal Effects</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/20-sequential-decisions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Sequential Decision Strategies</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#the-proportional-hazards-assumption-in-cox-regression" id="toc-the-proportional-hazards-assumption-in-cox-regression" class="nav-link active" data-scroll-target="#the-proportional-hazards-assumption-in-cox-regression"><span class="header-section-number">5.1</span> The proportional-hazards assumption in Cox regression</a>
  <ul class="collapse">
  <li><a href="#cox-regression-when-hazards-are-nonproportional" id="toc-cox-regression-when-hazards-are-nonproportional" class="nav-link" data-scroll-target="#cox-regression-when-hazards-are-nonproportional"><span class="header-section-number">5.1.1</span> Cox regression when hazards are nonproportional</a></li>
  <li><a href="#accelerated-failure-time-model" id="toc-accelerated-failure-time-model" class="nav-link" data-scroll-target="#accelerated-failure-time-model"><span class="header-section-number">5.1.2</span> Accelerated failure-time model</a></li>
  <li><a href="#restricted-mean-survival-time" id="toc-restricted-mean-survival-time" class="nav-link" data-scroll-target="#restricted-mean-survival-time"><span class="header-section-number">5.1.3</span> Restricted mean survival time</a></li>
  <li><a href="#landmark-analysis" id="toc-landmark-analysis" class="nav-link" data-scroll-target="#landmark-analysis"><span class="header-section-number">5.1.4</span> Landmark analysis</a></li>
  </ul></li>
  <li><a href="#cox-regression-with-time-dependent-covariates" id="toc-cox-regression-with-time-dependent-covariates" class="nav-link" data-scroll-target="#cox-regression-with-time-dependent-covariates"><span class="header-section-number">5.2</span> Cox regression with time-dependent covariates</a></li>
  <li><a href="#competing-risk-models" id="toc-competing-risk-models" class="nav-link" data-scroll-target="#competing-risk-models"><span class="header-section-number">5.3</span> Competing-risk models</a>
  <ul class="collapse">
  <li><a href="#cumulative-incidence-function" id="toc-cumulative-incidence-function" class="nav-link" data-scroll-target="#cumulative-incidence-function"><span class="header-section-number">5.3.1</span> Cumulative incidence function</a></li>
  <li><a href="#finegray-model" id="toc-finegray-model" class="nav-link" data-scroll-target="#finegray-model"><span class="header-section-number">5.3.2</span> Fine–Gray model</a></li>
  <li><a href="#cause-specific-hazard-model" id="toc-cause-specific-hazard-model" class="nav-link" data-scroll-target="#cause-specific-hazard-model"><span class="header-section-number">5.3.3</span> Cause-specific hazard model</a></li>
  </ul></li>
  <li><a href="#limitations-of-the-hazard-ratio" id="toc-limitations-of-the-hazard-ratio" class="nav-link" data-scroll-target="#limitations-of-the-hazard-ratio"><span class="header-section-number">5.4</span> Limitations of the hazard ratio</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Clinical Research with Survival Outcomes</span></h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Code</button></div></div>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>Survival analysis analyzes and makes inferences about the time to a specified event and the relation between survival outcome and prognostic factors. It is a method for censored data, also called survival-rate analysis. Different questions call for different methods: life tables estimate survival at a specified time, such as 5-year survival; life tables and Kaplan–Meier methods estimate median survival; Kaplan–Meier methods compare survival across levels of one factor; and Cox regression assesses effects of multiple factors. Life tables and Kaplan–Meier methods are relatively straightforward and are not discussed further here.</p>
<p>The Cox proportional-hazards model, proposed by Cox in 1972, is a semiparametric regression model for the effect of one or more covariates on the rate of death or another event at a given time. It accommodates numeric and categorical covariates and is widely used in biomedical research. Life tables and the Kaplan–Meier method are nonparametric; the latter was proposed by Kaplan and Meier in 1958.</p>
<section id="the-proportional-hazards-assumption-in-cox-regression" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="the-proportional-hazards-assumption-in-cox-regression"><span class="header-section-number">5.1</span> The proportional-hazards assumption in Cox regression</h2>
<p>The most important consideration in Cox regression is proportional hazards (PH): the ratio of hazards between groups does not change over time, so a factor has the same relative effect at every time point.</p>
<p><strong>Case 5.1</strong></p>
<p>This bone-marrow transplantation example includes patients with different leukemia types. <code>g</code> is group (1 = acute lymphoblastic leukemia; 2 = low-risk acute myeloid leukemia); <code>T1</code> is survival time in days after transplantation; and <code>delta1</code> is outcome (1 = death, 0 = alive). The clinical question is whether postoperative mortality differs between the two leukemia groups. To simplify the example, assume there is no confounding.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">g</th>
<th style="text-align: right;">T1</th>
<th style="text-align: right;">delta1</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">…</td>
<td style="text-align: right;">…</td>
<td style="text-align: right;">…</td>
</tr>
<tr class="even">
<td style="text-align: left;">1</td>
<td style="text-align: right;">107</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: right;">269</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="even">
<td style="text-align: left;">1</td>
<td style="text-align: right;">350</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2</td>
<td style="text-align: right;">2569</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: right;">2506</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2</td>
<td style="text-align: right;">2409</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">…</td>
<td style="text-align: right;">…</td>
<td style="text-align: right;">…</td>
</tr>
</tbody>
</table>
<p>First declare the survival-data format in Stata using <code>stset</code>, with <code>t1</code> as survival time and <code>delta1==1</code> as the clinical event. Plot group-specific Kaplan–Meier curves using <code>sts graph</code>.</p>
<div class="callout callout-style-simple callout-note no-icon callout-titled" title="Code 5.1">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Code 5.1
</div>
</div>
<div class="callout-body-container callout-body">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="kw">stset</span> t1, failure(delta1==1)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="kw">sts</span> <span class="kw">graph</span>, <span class="kw">by</span>(g)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
<p>Three methods can assess PH. First, inspect whether Kaplan–Meier curves cross. Here the red curve falls more rapidly shortly after surgery than the blue curve, suggesting higher short-term mortality in low-risk AML, but the blue curve falls substantially in long follow-up. The curves cross, so PH is not satisfied.</p>
<div class="text-center">
<p><img src="images/ch5-image1.png" class="img-fluid" style="width:100.0%"></p>
<p>Code 5.1 output: Kaplan–Meier curves for the two groups.</p>
</div>
<p>Second, plot Schoenfeld residuals against time. No clear time trend supports PH; an upward trend, as shown here, suggests a possible violation.</p>
<div class="callout callout-style-simple callout-note no-icon callout-titled" title="Code 5.2">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Code 5.2
</div>
</div>
<div class="callout-body-container callout-body">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="kw">stcox</span> g</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="kw">estat</span> phtest, <span class="fu">rank</span> plot(g)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
<div class="text-center">
<p><img src="images/ch5-image2.png" class="img-fluid" style="width:100.0%"></p>
<p>Code 5.2 output: Schoenfeld residuals versus time.</p>
</div>
<p>Third, draw log-minus-log survival curves (log time on the x-axis and log of minus log survival on the y-axis). Approximately parallel curves support PH; crossing curves suggest its violation.</p>
<div class="callout callout-style-simple callout-note no-icon callout-titled" title="Code 5.3">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Code 5.3
</div>
</div>
<div class="callout-body-container callout-body">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb3"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="kw">stphplot</span>, <span class="kw">by</span>(g)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
<div class="text-center">
<p><img src="images/ch5-image3.png" class="img-fluid" style="width:100.0%"></p>
<p>Code 5.3 output: log-minus-log survival curves.</p>
</div>
<section id="cox-regression-when-hazards-are-nonproportional" class="level3" data-number="5.1.1">
<h3 data-number="5.1.1" class="anchored" data-anchor-id="cox-regression-when-hazards-are-nonproportional"><span class="header-section-number">5.1.1</span> Cox regression when hazards are nonproportional</h3>
<p>When PH does not hold, three useful strategies are accelerated failure-time (AFT) models, restricted mean survival time (RMST), and landmark analysis.</p>
</section>
<section id="accelerated-failure-time-model" class="level3" data-number="5.1.2">
<h3 data-number="5.1.2" class="anchored" data-anchor-id="accelerated-failure-time-model"><span class="header-section-number">5.1.2</span> Accelerated failure-time model</h3>
<p>An AFT model studies the effect of intervention on the average time until an event. Intuitively, it compares the speed at which two interventions reach the outcome. Its regression coefficient represents the ratio of time required for the event; for death, it is a ratio of average survival time. After declaring survival data, use <code>streg</code>; exponential, Weibull, gamma, and other distributions can be chosen.</p>
<div class="callout callout-style-simple callout-note no-icon callout-titled" title="Code 5.4">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Code 5.4
</div>
</div>
<div class="callout-body-container callout-body">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb4"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="kw">stset</span> t1, failure(delta1==1)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="kw">streg</span> g, distribution(exponential) time</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
<div class="callout callout-style-simple callout-note no-icon callout-titled" title="Code 5.4 output">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Code 5.4 output
</div>
</div>
<div class="callout-body-container callout-body">
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Exponential AFT regression</th>
<th style="text-align: right;">Estimate</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Subjects / failures</td>
<td style="text-align: right;">92 / 46</td>
</tr>
<tr class="even">
<td style="text-align: left;">LR chi-square(1), p value</td>
<td style="text-align: right;">8.47; 0.0036</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>g</code> coefficient (95% CI)</td>
<td style="text-align: right;">0.871 (0.293 to 1.449)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Constant (95% CI)</td>
<td style="text-align: right;">6.137 (5.223 to 7.050)</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The coefficient for <code>g</code> is 0.871, indicating that the time to event in group <code>g=1</code> is prolonged by <span class="math inline">\((1-0.871)\%=12.9\%\)</span>. A failure curve also shows that events occur faster in <code>g=0</code>.</p>
<div class="callout callout-style-simple callout-note no-icon callout-titled" title="Code 5.5">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Code 5.5
</div>
</div>
<div class="callout-body-container callout-body">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb5"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="kw">stcurve</span>, failure <span class="fu">at</span>(g=(0 1))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
<div class="text-center">
<p><img src="images/ch5-image4.png" class="img-fluid" style="width:100.0%"></p>
<p>Code 5.5 output: accelerated failure curves.</p>
</div>
</section>
<section id="restricted-mean-survival-time" class="level3" data-number="5.1.3">
<h3 data-number="5.1.3" class="anchored" data-anchor-id="restricted-mean-survival-time"><span class="header-section-number">5.1.3</span> Restricted mean survival time</h3>
<p>RMST is the area under a survival curve up to a chosen time horizon (the pink area in Figure 5.1): the average survival time within that period. Longer RMST indicates better treatment. It does not depend on PH and is readily understood, but requires choosing a follow-up cutoff from clinical information; there is no universal choice.</p>
<div class="text-center">
<p><img src="images/ch5-image5.png" class="img-fluid" style="width:100.0%"></p>
<p>Figure 5.1 RMST for the two groups with cutoffs of 180 and 730 days.</p>
</div>
<p>In Case 5.1, higher short-term mortality in low-risk AML may reflect acute postoperative reactions, usually lasting about three to six months. Let <span class="math inline">\(\tau=180\)</span> days and use <code>strmst2</code>.</p>
<div class="callout callout-style-simple callout-note no-icon callout-titled" title="Code 5.6">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Code 5.6
</div>
</div>
<div class="callout-body-container callout-body">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb6"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>strmst2 g, tau(180)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
<div class="callout callout-style-simple callout-note no-icon callout-titled" title="Code 5.6 output">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Code 5.6 output
</div>
</div>
<div class="callout-body-container callout-body">
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">RMST at 180 days</th>
<th style="text-align: right;">Estimate</th>
<th style="text-align: left;">95% CI / p value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Arm 2</td>
<td style="text-align: right;">164.259</td>
<td style="text-align: left;">153.018 to 175.501</td>
</tr>
<tr class="even">
<td style="text-align: left;">Arm 1</td>
<td style="text-align: right;">166.211</td>
<td style="text-align: left;">154.886 to 177.535</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Difference (arm 2 − arm 1)</td>
<td style="text-align: right;">-1.951</td>
<td style="text-align: left;">-17.908 to 14.005; 0.811</td>
</tr>
<tr class="even">
<td style="text-align: left;">Ratio (arm 2 / arm 1)</td>
<td style="text-align: right;">0.988</td>
<td style="text-align: left;">0.897 to 1.088; 0.811</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>At 180 days, RMST is 166 days in group 1 and 164 days in group 2, with no meaningful difference. To compare long-term effects, set a longer horizon such as 730 days. Group 1 has RMST 473 and group 2 has RMST 587; the difference and ratio have <em>p</em> values 0.035 and 0.042, respectively, so group 1 has shorter RMST through 730 days.</p>
<div class="callout callout-style-simple callout-note no-icon callout-titled" title="Code 5.7">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Code 5.7
</div>
</div>
<div class="callout-body-container callout-body">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb7"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>strmst2 g, tau(730)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
<div class="callout callout-style-simple callout-note no-icon callout-titled" title="Code 5.7 output">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Code 5.7 output
</div>
</div>
<div class="callout-body-container callout-body">
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">RMST at 730 days</th>
<th style="text-align: right;">Estimate</th>
<th style="text-align: left;">95% CI / p value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Arm 2</td>
<td style="text-align: right;">586.704</td>
<td style="text-align: left;">523.148 to 650.260</td>
</tr>
<tr class="even">
<td style="text-align: left;">Arm 1</td>
<td style="text-align: right;">473.868</td>
<td style="text-align: left;">391.176 to 556.561</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Difference (arm 2 − arm 1)</td>
<td style="text-align: right;">112.835</td>
<td style="text-align: left;">8.540 to 217.130; 0.034</td>
</tr>
<tr class="even">
<td style="text-align: left;">Ratio (arm 2 / arm 1)</td>
<td style="text-align: right;">1.238</td>
<td style="text-align: left;">1.008 to 1.520; 0.042</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>An important drawback is that data collected after the cutoff are excluded, wasting data and reducing power. RMST is especially useful as an alternative to the hazard ratio under nonproportional hazards (Royston and Parmar 2013).</p>
</section>
<section id="landmark-analysis" class="level3" data-number="5.1.4">
<h3 data-number="5.1.4" class="anchored" data-anchor-id="landmark-analysis"><span class="header-section-number">5.1.4</span> Landmark analysis</h3>
<p>Landmark analysis divides a Kaplan–Meier curve into periods and fits Cox models separately before and after a landmark. It recognizes that event-time distributions can differ between interventions. For surgery versus non-surgery, short-term complications may lower early survival after surgery, while later survival can be better. By choosing a landmark time and including only participants alive at that time for the later comparison, it avoids using information not yet available (Dafni 2011).</p>
<p>In Case 5.1, choose 180 days from clinical knowledge. For the first 180 days, manually censor participants without an event at 180 days; the result shows no clear difference (<em>p</em>=0.373).</p>
<div class="callout callout-style-simple callout-note no-icon callout-titled" title="Code 5.8">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Code 5.8
</div>
</div>
<div class="callout-body-container callout-body">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb8"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="kw">gen</span> L1 = t1 <span class="kw">if</span> t1 &lt; 180</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="kw">replace</span> L1 = 180 <span class="kw">if</span> t1 &gt;= 180</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="kw">gen</span> deltaL1 = delta1 <span class="kw">if</span> t1 &lt; 180</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="kw">replace</span> deltaL1 = 0 <span class="kw">if</span> t1 &gt;= 180</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a><span class="kw">stset</span> L1, failure(deltaL1==1)</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a><span class="kw">stcox</span> g</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
<div class="callout callout-style-simple callout-note no-icon callout-titled" title="Code 5.8 output">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Code 5.8 output
</div>
</div>
<div class="callout-body-container callout-body">
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Cox regression through 180 days</th>
<th style="text-align: right;">Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Subjects / failures</td>
<td style="text-align: right;">92 / 15</td>
</tr>
<tr class="even">
<td style="text-align: left;">HR for <code>g</code> (95% CI)</td>
<td style="text-align: right;">0.630 (0.229 to 1.739)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">p value</td>
<td style="text-align: right;">0.373</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>For time after 180 days, remove participants whose survival time is shorter than 180 days and restart follow-up at 180 days. Acute lymphoblastic leukemia then has lower survival than low-risk AML.</p>
<div class="callout callout-style-simple callout-note no-icon callout-titled" title="Code 5.9">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Code 5.9
</div>
</div>
<div class="callout-body-container callout-body">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb9"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="kw">gen</span> L2 = t1 - 180</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="kw">stset</span> L2, failure(delta1==1)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="kw">stcox</span> g <span class="kw">if</span> L2 &gt; 0</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="kw">sts</span> <span class="kw">graph</span> <span class="kw">if</span> L2 &gt; 0, <span class="kw">by</span>(g) risktable censored(single)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
<div class="callout callout-style-simple callout-note no-icon callout-titled" title="Code 5.9 output">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Code 5.9 output
</div>
</div>
<div class="callout-body-container callout-body">
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Cox regression after 180 days</th>
<th style="text-align: right;">Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Subjects / failures</td>
<td style="text-align: right;">77 / 31</td>
</tr>
<tr class="even">
<td style="text-align: left;">HR for <code>g</code> (95% CI)</td>
<td style="text-align: right;">0.466 (0.228 to 0.956)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">p value</td>
<td style="text-align: right;">0.037</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="text-center">
<p><img src="images/ch5-image6.png" class="img-fluid" style="width:100.0%"></p>
<p>Code 5.9 output: Kaplan–Meier curves after 180 days.</p>
</div>
<p>PH Cox analysis assumes equal hazard ratios at all time points. RMST compares areas under curves before a specified cutoff; landmark analysis compares survival before and after a specified landmark (Figure 5.2).</p>
<div class="text-center">
<p><img src="images/ch5-image7.png" class="img-fluid" style="width:100.0%"></p>
<p>Figure 5.2 Alternatives to the Cox model in survival analysis.</p>
</div>
<p>Post hoc assessment of PH can be informative, but formal PH tests can miss clinically important deviations in small studies and flag clinically trivial deviations in large studies. Graphical displays, including Kaplan–Meier and Schoenfeld-residual plots, are often more useful. Piecewise hazard models can be used when PH fails, but post hoc selection of intervals can exaggerate time variation and late-period hazard ratios include only survivors, so they are no longer genuinely randomized comparisons. Nonproportionality may also result from clinically distinct subgroups, when subgroup analyses or stratified Cox models may help, or from nonadherence and crossover, which make treatment groups more similar over time. This is especially problematic in noninferiority trials because dilution can falsely support noninferiority. Per-protocol methods that adjust for nonadherence and crossover, estimating the average causal effect among adherers, may help recover the treatment effect. A hazard-ratio noninferiority margin can be inappropriate or hard to interpret when PH clearly fails.</p>
</section>
</section>
<section id="cox-regression-with-time-dependent-covariates" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="cox-regression-with-time-dependent-covariates"><span class="header-section-number">5.2</span> Cox regression with time-dependent covariates</h2>
<p>Ordinary Cox regression studies baseline variables, but many covariates change over time. Smoking status can change as a person quits and resumes; C-reactive protein (CRP) changes with clinical status in sepsis. RMST and landmark analysis are unsuitable when the exposure is time varying, when no clear cutoff or landmark exists, or when a landmark would exclude many participants.</p>
<p><strong>Case 5.2</strong> considers CRP and death or serious complications in 100 patients with sepsis. <code>id</code> identifies participants; <code>status</code> is the composite outcome; <code>start</code> and <code>stop</code> are time in hours; <code>age</code> is age. A second data table contains CRP by <code>id</code>, measurement <code>time</code>, and <code>crp</code>. Before analysis, restructure data so that each row represents one period during which the time-varying covariate is constant. Patient 1 has only one CRP value during follow-up and needs one row. Patient 2 has several measurements and therefore several records: each record starts at one CRP measurement and stops at the next; the final record runs from the final pre-event measurement to the event time. This creates <code>tstart</code>, <code>tstop</code>, <code>endpt</code>, and <code>crp</code> variables.</p>
<p>In the restructured data, repeated records from each participant require clustering by participant. The Cox <em>p</em> value is 0.040, indicating an association between CRP and the composite of death or serious complications.</p>
<div class="callout callout-style-simple callout-note no-icon callout-titled" title="Code 5.10">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Code 5.10
</div>
</div>
<div class="callout-body-container callout-body">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb10"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="kw">gen</span> time = tstop - tstart</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="kw">stset</span> time, failure(endpt == 1)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="kw">stcox</span> crp, <span class="kw">cluster</span>(id)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
<div class="callout callout-style-simple callout-note no-icon callout-titled" title="Code 5.10 output">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Code 5.10 output
</div>
</div>
<div class="callout-body-container callout-body">
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Clustered Cox regression</th>
<th style="text-align: right;">Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Records / failures</td>
<td style="text-align: right;">365 / 67</td>
</tr>
<tr class="even">
<td style="text-align: left;">HR for CRP (95% CI)</td>
<td style="text-align: right;">0.9943 (0.9888 to 0.9997)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">p value</td>
<td style="text-align: right;">0.040</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="competing-risk-models" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="competing-risk-models"><span class="header-section-number">5.3</span> Competing-risk models</h2>
<p>Conventional survival outcomes are often binary—death/non-death or recurrence/non-recurrence. In practice there may be multiple endpoints, some of which prevent the event of interest or alter its probability; these are competing risks. For stroke risk in diabetes, death prevents observation of stroke and is a competing risk. A simple solution is to use a composite endpoint such as stroke or death. When the risks of different events must be distinguished, use cumulative incidence functions, Fine–Gray subdistribution hazards, or cause-specific hazards (Fine and Gray 1999; Putter et al.&nbsp;2007; Austin et al.&nbsp;2016).</p>
<div class="text-center">
<p><img src="images/ch5-image8.png" class="img-fluid" style="width:100.0%"></p>
<p>Figure 5.3 Competing-risk events.</p>
</div>
<p><strong>Case 5.3</strong> includes 205 participants with melanoma. <code>time</code> is time after surgery; <code>status=1</code> is death from melanoma, <code>status=2</code> is censoring, and <code>status=3</code> is death from other causes. Death from melanoma and death from other causes compete because either prevents the other.</p>
<section id="cumulative-incidence-function" class="level3" data-number="5.3.1">
<h3 data-number="5.3.1" class="anchored" data-anchor-id="cumulative-incidence-function"><span class="header-section-number">5.3.1</span> Cumulative incidence function</h3>
<p>The cumulative incidence function (CIF) depicts the time-varying occurrence of the event of interest while accounting for competing events. It is nonparametric and replaces ordinary survival curves in this setting. Events are mutually exclusive, and the sum of cause-specific cumulative incidences equals the cumulative incidence of the composite event.</p>
<div class="callout callout-style-simple callout-note no-icon callout-titled" title="Code 5.11">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Code 5.11
</div>
</div>
<div class="callout-body-container callout-body">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb11"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="kw">stset</span> time, fail(status==1)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="kw">stcurve</span>, cif</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="kw">stset</span> time, fail(status==3)</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="kw">stcurve</span>, cif</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
<div class="text-center">
<p><img src="images/ch5-image9.png" class="img-fluid" style="width:100.0%"></p>
<p>Code 5.11 output: cumulative-incidence curves for competing events.</p>
</div>
</section>
<section id="finegray-model" class="level3" data-number="5.3.2">
<h3 data-number="5.3.2" class="anchored" data-anchor-id="finegray-model"><span class="header-section-number">5.3.2</span> Fine–Gray model</h3>
<p>The Fine–Gray model is a semiparametric proportional-hazards model for the time-varying rate of the event of interest among people who have not experienced it. It tests associations between that event and covariates; its coefficient, SHR, is a subdistribution hazard ratio. For melanoma death, compare participants with and without ulceration using <code>stcrreg</code>. The result is strongly different (<em>p</em> &lt; 0.001); by contrast, death from other causes does not differ by ulceration.</p>
<div class="callout callout-style-simple callout-note no-icon callout-titled" title="Code 5.12">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Code 5.12
</div>
</div>
<div class="callout-body-container callout-body">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb12"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="kw">stset</span> time, fail(status == 1)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>stcrreg ulcer, compete(status == 3)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
<div class="callout callout-style-simple callout-note no-icon callout-titled" title="Code 5.12 output">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Code 5.12 output
</div>
</div>
<div class="callout-body-container callout-body">
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Fine–Gray model: melanoma death</th>
<th style="text-align: right;">Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Participants / melanoma deaths / competing deaths</td>
<td style="text-align: right;">205 / 57 / 14</td>
</tr>
<tr class="even">
<td style="text-align: left;">SHR for ulceration (95% CI)</td>
<td style="text-align: right;">4.111 (2.333 to 7.246)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">p value</td>
<td style="text-align: right;">&lt;0.001</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="callout callout-style-simple callout-note no-icon callout-titled" title="Code 5.13">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Code 5.13
</div>
</div>
<div class="callout-body-container callout-body">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb13"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="kw">stset</span> time, fail(status == 3)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>stcrreg ulcer, compete(status == 1)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
<div class="callout callout-style-simple callout-note no-icon callout-titled" title="Code 5.13 output">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Code 5.13 output
</div>
</div>
<div class="callout-body-container callout-body">
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Fine–Gray model: other-cause death</th>
<th style="text-align: right;">Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">SHR for ulceration (95% CI)</td>
<td style="text-align: right;">1.255 (0.438 to 3.599)</td>
</tr>
<tr class="even">
<td style="text-align: left;">p value</td>
<td style="text-align: right;">0.673</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The corresponding CIF curves show higher melanoma-death cumulative incidence with ulceration and no clear difference in other-cause death.</p>
<div class="callout callout-style-simple callout-note no-icon callout-titled" title="Code 5.14">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Code 5.14
</div>
</div>
<div class="callout-body-container callout-body">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb14"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="kw">stset</span> time, fail(status==1)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>stcrreg ulcer, compete(status==3)</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a><span class="kw">stcurve</span>, cif at1(ulcer=0) at2(ulcer=1)</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a><span class="kw">stset</span> time, fail(status==3)</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>stcrreg ulcer, compete(status==1)</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a><span class="kw">stcurve</span>, cif at1(ulcer=0) at2(ulcer=1)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
<div class="text-center">
<p><img src="images/ch5-image10.png" class="img-fluid" style="width:100.0%"></p>
<p>Code 5.14 output: group-specific cumulative-incidence curves.</p>
</div>
</section>
<section id="cause-specific-hazard-model" class="level3" data-number="5.3.3">
<h3 data-number="5.3.3" class="anchored" data-anchor-id="cause-specific-hazard-model"><span class="header-section-number">5.3.3</span> Cause-specific hazard model</h3>
<p>A simpler competing-risk analysis is the cause-specific hazard model: treat events not of interest as artificially censored and fit a Cox model in the resulting data. The result agrees with Fine–Gray: melanoma-death risk differs by ulceration, with <em>p</em> &lt; 0.001.</p>
<div class="callout callout-style-simple callout-note no-icon callout-titled" title="Code 5.15">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Code 5.15
</div>
</div>
<div class="callout-body-container callout-body">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb15"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="kw">generate</span> status_cause = 2</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="kw">replace</span> status_cause = 1 <span class="kw">if</span> status == 1</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="kw">stset</span> time, fail(status_cause==1)</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a><span class="kw">stcox</span> ulcer</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
<div class="callout callout-style-simple callout-note no-icon callout-titled" title="Code 5.15 output">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Code 5.15 output
</div>
</div>
<div class="callout-body-container callout-body">
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Cause-specific Cox model</th>
<th style="text-align: right;">Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Participants / melanoma deaths</td>
<td style="text-align: right;">205 / 57</td>
</tr>
<tr class="even">
<td style="text-align: left;">HR for ulceration (95% CI)</td>
<td style="text-align: right;">4.357 (2.442 to 7.773)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">p value</td>
<td style="text-align: right;">&lt;0.001</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
</section>
<section id="limitations-of-the-hazard-ratio" class="level2" data-number="5.4">
<h2 data-number="5.4" class="anchored" data-anchor-id="limitations-of-the-hazard-ratio"><span class="header-section-number">5.4</span> Limitations of the hazard ratio</h2>
<p>Three common summaries of survival outcomes are the hazard ratio (HR), median survival in each treatment group, and time-point survival such as 1-year progression-free or overall survival. HR uses information from the whole survival curve and summarizes relative treatment effect over follow-up; median survival uses one point of each curve, and a time-point survival probability is also limited. HR can be unadjusted (a univariable Cox model) or adjusted (a multivariable Cox model incorporating confounders such as age, sex, stage, and performance status). Medians and time-point probabilities derived from curves are usually unadjusted.</p>
<p>HR has important limitations. First, if curves substantially violate PH, an overall HR is hard to interpret because it changes markedly over time, and PH tests can have low power. Second, censoring can create selection bias if it is related to both intervention and outcome. Third, HR changes with the follow-up period—the values at 180 and 730 days in Case 5.1 differ—so a reported HR is an average. Fourth, HR is relative: statistical significance need not imply clinical importance. Clinicians should consider absolute measures with coherent clinical meaning, including time-point survival and median survival. Across tumors, HR=0.75 might mean a 50-day median-survival benefit or only about 10 days.</p>
<p>Finally, extending an HR beyond observed follow-up requires great caution. Without later information, continued PH cannot be assumed; subsequent or palliative therapies can markedly affect survival. Because the risk set changes as people die, later HRs may carry intrinsic selection bias even in randomized trials—“the hazards of hazard ratios” (Hernán 2010). Interpret HR together with survival curves, RMST, and absolute risk at specified times.</p>
</section>
<section id="references" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="references">References</h2>
<ol type="1">
<li>Zhang Z, Reinikainen J, Adeleke KA, Pieterse ME, Groothuis-Oudshoorn CGM. Time-varying covariates and coefficients in Cox regression models. <em>Ann Transl Med</em>. 2018;6(7):121.</li>
<li>Gregson J, Sharples L, Stone GW, Burman CF, Öhrn F, Pocock S. Nonproportional hazards for time-to-event outcomes in clinical trials. <em>J Am Coll Cardiol</em>. 2019;74(16):2102-2112.</li>
<li>Cox DR. Regression models and life-tables. <em>Journal of the Royal Statistical Society: Series B</em>. 1972;34(2):187-220.</li>
<li>Kaplan EL, Meier P. Nonparametric estimation from incomplete observations. <em>JASA</em>. 1958;53(282):457-481.</li>
<li>Fine JP, Gray RJ. A proportional hazards model for the subdistribution of a competing risk. <em>JASA</em>. 1999;94(446):496-509.</li>
<li>Putter H, Fiocco M, Geskus RB. Competing risks and multi-state models. <em>Statistics in Medicine</em>. 2007;26(11):2389-2430.</li>
<li>Austin PC, Lee DS, Fine JP. Analysis of survival data in the presence of competing risks. <em>Circulation</em>. 2016;133(6):601-609.</li>
<li>Royston P, Parmar MK. Restricted mean survival time. <em>BMC Medical Research Methodology</em>. 2013;13:152.</li>
<li>Dafni U. Landmark analysis at the 25-year landmark point. <em>Circulation: Cardiovascular Quality and Outcomes</em>. 2011;4(3):363-371.</li>
<li>Hernán MA. The hazards of hazard ratios. <em>Epidemiology</em>. 2010;21(1):13-15.</li>
</ol>


<!-- -->

</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
        for (let i=0; i<detailsSrc.length; i++) {
          const details = detailsSrc[i].parentElement;
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../chapters/04-protocol-consent.html" class="pagination-link" aria-label="Writing Randomized Controlled Trial Protocols and Informed Consent">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Writing Randomized Controlled Trial Protocols and Informed Consent</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../chapters/06-meta-analysis.html" class="pagination-link" aria-label="Principles and Methods of Meta-analysis">
        <span class="nav-page-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Principles and Methods of Meta-analysis</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb16" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu"># Clinical Research with Survival Outcomes</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>Survival analysis analyzes and makes inferences about the time to a specified event and the relation between survival outcome and prognostic factors. It is a method for censored data, also called survival-rate analysis. Different questions call for different methods: life tables estimate survival at a specified time, such as 5-year survival; life tables and Kaplan–Meier methods estimate median survival; Kaplan–Meier methods compare survival across levels of one factor; and Cox regression assesses effects of multiple factors. Life tables and Kaplan–Meier methods are relatively straightforward and are not discussed further here.</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>The Cox proportional-hazards model, proposed by Cox in 1972, is a semiparametric regression model for the effect of one or more covariates on the rate of death or another event at a given time. It accommodates numeric and categorical covariates and is widely used in biomedical research. Life tables and the Kaplan–Meier method are nonparametric; the latter was proposed by Kaplan and Meier in 1958.</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a><span class="fu">## The proportional-hazards assumption in Cox regression</span></span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>The most important consideration in Cox regression is proportional hazards (PH): the ratio of hazards between groups does not change over time, so a factor has the same relative effect at every time point.</span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>**Case 5.1**</span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a>This bone-marrow transplantation example includes patients with different leukemia types. <span class="in">`g`</span> is group (1 = acute lymphoblastic leukemia; 2 = low-risk acute myeloid leukemia); <span class="in">`T1`</span> is survival time in days after transplantation; and <span class="in">`delta1`</span> is outcome (1 = death, 0 = alive). The clinical question is whether postoperative mortality differs between the two leukemia groups. To simplify the example, assume there is no confounding.</span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-15"><a href="#cb16-15" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> g <span class="pp">|</span> T1 <span class="pp">|</span> delta1 <span class="pp">|</span></span>
<span id="cb16-16"><a href="#cb16-16" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span>:--<span class="pp">|</span>--:<span class="pp">|</span>--:<span class="pp">|</span></span>
<span id="cb16-17"><a href="#cb16-17" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> … <span class="pp">|</span> … <span class="pp">|</span> … <span class="pp">|</span></span>
<span id="cb16-18"><a href="#cb16-18" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 1 <span class="pp">|</span> 107 <span class="pp">|</span> 1 <span class="pp">|</span></span>
<span id="cb16-19"><a href="#cb16-19" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 1 <span class="pp">|</span> 269 <span class="pp">|</span> 1 <span class="pp">|</span></span>
<span id="cb16-20"><a href="#cb16-20" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 1 <span class="pp">|</span> 350 <span class="pp">|</span> 0 <span class="pp">|</span></span>
<span id="cb16-21"><a href="#cb16-21" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 2 <span class="pp">|</span> 2569 <span class="pp">|</span> 0 <span class="pp">|</span></span>
<span id="cb16-22"><a href="#cb16-22" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 2 <span class="pp">|</span> 2506 <span class="pp">|</span> 0 <span class="pp">|</span></span>
<span id="cb16-23"><a href="#cb16-23" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 2 <span class="pp">|</span> 2409 <span class="pp">|</span> 0 <span class="pp">|</span></span>
<span id="cb16-24"><a href="#cb16-24" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> … <span class="pp">|</span> … <span class="pp">|</span> … <span class="pp">|</span></span>
<span id="cb16-25"><a href="#cb16-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-26"><a href="#cb16-26" aria-hidden="true" tabindex="-1"></a>First declare the survival-data format in Stata using <span class="in">`stset`</span>, with <span class="in">`t1`</span> as survival time and <span class="in">`delta1==1`</span> as the clinical event. Plot group-specific Kaplan–Meier curves using <span class="in">`sts graph`</span>.</span>
<span id="cb16-27"><a href="#cb16-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-28"><a href="#cb16-28" aria-hidden="true" tabindex="-1"></a>::: {.callout-note appearance="simple" icon="false" title="Code 5.1"}</span>
<span id="cb16-29"><a href="#cb16-29" aria-hidden="true" tabindex="-1"></a><span class="in">```stata</span></span>
<span id="cb16-30"><a href="#cb16-30" aria-hidden="true" tabindex="-1"></a><span class="in">stset t1, failure(delta1==1)</span></span>
<span id="cb16-31"><a href="#cb16-31" aria-hidden="true" tabindex="-1"></a><span class="in">sts graph, by(g)</span></span>
<span id="cb16-32"><a href="#cb16-32" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb16-33"><a href="#cb16-33" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb16-34"><a href="#cb16-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-35"><a href="#cb16-35" aria-hidden="true" tabindex="-1"></a>Three methods can assess PH. First, inspect whether Kaplan–Meier curves cross. Here the red curve falls more rapidly shortly after surgery than the blue curve, suggesting higher short-term mortality in low-risk AML, but the blue curve falls substantially in long follow-up. The curves cross, so PH is not satisfied.</span>
<span id="cb16-36"><a href="#cb16-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-37"><a href="#cb16-37" aria-hidden="true" tabindex="-1"></a>::: {.text-center}</span>
<span id="cb16-38"><a href="#cb16-38" aria-hidden="true" tabindex="-1"></a><span class="al">![](images/ch5-image1.png)</span>{width="100%"}</span>
<span id="cb16-39"><a href="#cb16-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-40"><a href="#cb16-40" aria-hidden="true" tabindex="-1"></a>Code 5.1 output: Kaplan–Meier curves for the two groups.</span>
<span id="cb16-41"><a href="#cb16-41" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb16-42"><a href="#cb16-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-43"><a href="#cb16-43" aria-hidden="true" tabindex="-1"></a>Second, plot Schoenfeld residuals against time. No clear time trend supports PH; an upward trend, as shown here, suggests a possible violation.</span>
<span id="cb16-44"><a href="#cb16-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-45"><a href="#cb16-45" aria-hidden="true" tabindex="-1"></a>::: {.callout-note appearance="simple" icon="false" title="Code 5.2"}</span>
<span id="cb16-46"><a href="#cb16-46" aria-hidden="true" tabindex="-1"></a><span class="in">```stata</span></span>
<span id="cb16-47"><a href="#cb16-47" aria-hidden="true" tabindex="-1"></a><span class="in">stcox g</span></span>
<span id="cb16-48"><a href="#cb16-48" aria-hidden="true" tabindex="-1"></a><span class="in">estat phtest, rank plot(g)</span></span>
<span id="cb16-49"><a href="#cb16-49" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb16-50"><a href="#cb16-50" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb16-51"><a href="#cb16-51" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-52"><a href="#cb16-52" aria-hidden="true" tabindex="-1"></a>::: {.text-center}</span>
<span id="cb16-53"><a href="#cb16-53" aria-hidden="true" tabindex="-1"></a><span class="al">![](images/ch5-image2.png)</span>{width="100%"}</span>
<span id="cb16-54"><a href="#cb16-54" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-55"><a href="#cb16-55" aria-hidden="true" tabindex="-1"></a>Code 5.2 output: Schoenfeld residuals versus time.</span>
<span id="cb16-56"><a href="#cb16-56" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb16-57"><a href="#cb16-57" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-58"><a href="#cb16-58" aria-hidden="true" tabindex="-1"></a>Third, draw log-minus-log survival curves (log time on the x-axis and log of minus log survival on the y-axis). Approximately parallel curves support PH; crossing curves suggest its violation.</span>
<span id="cb16-59"><a href="#cb16-59" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-60"><a href="#cb16-60" aria-hidden="true" tabindex="-1"></a>::: {.callout-note appearance="simple" icon="false" title="Code 5.3"}</span>
<span id="cb16-61"><a href="#cb16-61" aria-hidden="true" tabindex="-1"></a><span class="in">```stata</span></span>
<span id="cb16-62"><a href="#cb16-62" aria-hidden="true" tabindex="-1"></a><span class="in">stphplot, by(g)</span></span>
<span id="cb16-63"><a href="#cb16-63" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb16-64"><a href="#cb16-64" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb16-65"><a href="#cb16-65" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-66"><a href="#cb16-66" aria-hidden="true" tabindex="-1"></a>::: {.text-center}</span>
<span id="cb16-67"><a href="#cb16-67" aria-hidden="true" tabindex="-1"></a><span class="al">![](images/ch5-image3.png)</span>{width="100%"}</span>
<span id="cb16-68"><a href="#cb16-68" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-69"><a href="#cb16-69" aria-hidden="true" tabindex="-1"></a>Code 5.3 output: log-minus-log survival curves.</span>
<span id="cb16-70"><a href="#cb16-70" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb16-71"><a href="#cb16-71" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-72"><a href="#cb16-72" aria-hidden="true" tabindex="-1"></a><span class="fu">### Cox regression when hazards are nonproportional</span></span>
<span id="cb16-73"><a href="#cb16-73" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-74"><a href="#cb16-74" aria-hidden="true" tabindex="-1"></a>When PH does not hold, three useful strategies are accelerated failure-time (AFT) models, restricted mean survival time (RMST), and landmark analysis.</span>
<span id="cb16-75"><a href="#cb16-75" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-76"><a href="#cb16-76" aria-hidden="true" tabindex="-1"></a><span class="fu">### Accelerated failure-time model</span></span>
<span id="cb16-77"><a href="#cb16-77" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-78"><a href="#cb16-78" aria-hidden="true" tabindex="-1"></a>An AFT model studies the effect of intervention on the average time until an event. Intuitively, it compares the speed at which two interventions reach the outcome. Its regression coefficient represents the ratio of time required for the event; for death, it is a ratio of average survival time. After declaring survival data, use <span class="in">`streg`</span>; exponential, Weibull, gamma, and other distributions can be chosen.</span>
<span id="cb16-79"><a href="#cb16-79" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-80"><a href="#cb16-80" aria-hidden="true" tabindex="-1"></a>::: {.callout-note appearance="simple" icon="false" title="Code 5.4"}</span>
<span id="cb16-81"><a href="#cb16-81" aria-hidden="true" tabindex="-1"></a><span class="in">```stata</span></span>
<span id="cb16-82"><a href="#cb16-82" aria-hidden="true" tabindex="-1"></a><span class="in">stset t1, failure(delta1==1)</span></span>
<span id="cb16-83"><a href="#cb16-83" aria-hidden="true" tabindex="-1"></a><span class="in">streg g, distribution(exponential) time</span></span>
<span id="cb16-84"><a href="#cb16-84" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb16-85"><a href="#cb16-85" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb16-86"><a href="#cb16-86" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-87"><a href="#cb16-87" aria-hidden="true" tabindex="-1"></a>::: {.callout-note appearance="simple" icon="false" title="Code 5.4 output"}</span>
<span id="cb16-88"><a href="#cb16-88" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Exponential AFT regression <span class="pp">|</span> Estimate <span class="pp">|</span></span>
<span id="cb16-89"><a href="#cb16-89" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span>:--<span class="pp">|</span>--:<span class="pp">|</span></span>
<span id="cb16-90"><a href="#cb16-90" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Subjects / failures <span class="pp">|</span> 92 / 46 <span class="pp">|</span></span>
<span id="cb16-91"><a href="#cb16-91" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> LR chi-square(1), p value <span class="pp">|</span> 8.47; 0.0036 <span class="pp">|</span></span>
<span id="cb16-92"><a href="#cb16-92" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`g`</span> coefficient (95% CI) <span class="pp">|</span> 0.871 (0.293 to 1.449) <span class="pp">|</span></span>
<span id="cb16-93"><a href="#cb16-93" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Constant (95% CI) <span class="pp">|</span> 6.137 (5.223 to 7.050) <span class="pp">|</span></span>
<span id="cb16-94"><a href="#cb16-94" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb16-95"><a href="#cb16-95" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-96"><a href="#cb16-96" aria-hidden="true" tabindex="-1"></a>The coefficient for <span class="in">`g`</span> is 0.871, indicating that the time to event in group <span class="in">`g=1`</span> is prolonged by $(1-0.871)\%=12.9\%$. A failure curve also shows that events occur faster in <span class="in">`g=0`</span>.</span>
<span id="cb16-97"><a href="#cb16-97" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-98"><a href="#cb16-98" aria-hidden="true" tabindex="-1"></a>::: {.callout-note appearance="simple" icon="false" title="Code 5.5"}</span>
<span id="cb16-99"><a href="#cb16-99" aria-hidden="true" tabindex="-1"></a><span class="in">```stata</span></span>
<span id="cb16-100"><a href="#cb16-100" aria-hidden="true" tabindex="-1"></a><span class="in">stcurve, failure at(g=(0 1))</span></span>
<span id="cb16-101"><a href="#cb16-101" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb16-102"><a href="#cb16-102" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb16-103"><a href="#cb16-103" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-104"><a href="#cb16-104" aria-hidden="true" tabindex="-1"></a>::: {.text-center}</span>
<span id="cb16-105"><a href="#cb16-105" aria-hidden="true" tabindex="-1"></a><span class="al">![](images/ch5-image4.png)</span>{width="100%"}</span>
<span id="cb16-106"><a href="#cb16-106" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-107"><a href="#cb16-107" aria-hidden="true" tabindex="-1"></a>Code 5.5 output: accelerated failure curves.</span>
<span id="cb16-108"><a href="#cb16-108" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb16-109"><a href="#cb16-109" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-110"><a href="#cb16-110" aria-hidden="true" tabindex="-1"></a><span class="fu">### Restricted mean survival time</span></span>
<span id="cb16-111"><a href="#cb16-111" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-112"><a href="#cb16-112" aria-hidden="true" tabindex="-1"></a>RMST is the area under a survival curve up to a chosen time horizon (the pink area in Figure 5.1): the average survival time within that period. Longer RMST indicates better treatment. It does not depend on PH and is readily understood, but requires choosing a follow-up cutoff from clinical information; there is no universal choice.</span>
<span id="cb16-113"><a href="#cb16-113" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-114"><a href="#cb16-114" aria-hidden="true" tabindex="-1"></a>::: {.text-center}</span>
<span id="cb16-115"><a href="#cb16-115" aria-hidden="true" tabindex="-1"></a><span class="al">![](images/ch5-image5.png)</span>{width="100%"}</span>
<span id="cb16-116"><a href="#cb16-116" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-117"><a href="#cb16-117" aria-hidden="true" tabindex="-1"></a>Figure 5.1 RMST for the two groups with cutoffs of 180 and 730 days.</span>
<span id="cb16-118"><a href="#cb16-118" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb16-119"><a href="#cb16-119" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-120"><a href="#cb16-120" aria-hidden="true" tabindex="-1"></a>In Case 5.1, higher short-term mortality in low-risk AML may reflect acute postoperative reactions, usually lasting about three to six months. Let $\tau=180$ days and use <span class="in">`strmst2`</span>.</span>
<span id="cb16-121"><a href="#cb16-121" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-122"><a href="#cb16-122" aria-hidden="true" tabindex="-1"></a>::: {.callout-note appearance="simple" icon="false" title="Code 5.6"}</span>
<span id="cb16-123"><a href="#cb16-123" aria-hidden="true" tabindex="-1"></a><span class="in">```stata</span></span>
<span id="cb16-124"><a href="#cb16-124" aria-hidden="true" tabindex="-1"></a><span class="in">strmst2 g, tau(180)</span></span>
<span id="cb16-125"><a href="#cb16-125" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb16-126"><a href="#cb16-126" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb16-127"><a href="#cb16-127" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-128"><a href="#cb16-128" aria-hidden="true" tabindex="-1"></a>::: {.callout-note appearance="simple" icon="false" title="Code 5.6 output"}</span>
<span id="cb16-129"><a href="#cb16-129" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> RMST at 180 days <span class="pp">|</span> Estimate <span class="pp">|</span> 95% CI / p value <span class="pp">|</span></span>
<span id="cb16-130"><a href="#cb16-130" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span>:--<span class="pp">|</span>--:<span class="pp">|</span>:--<span class="pp">|</span></span>
<span id="cb16-131"><a href="#cb16-131" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Arm 2 <span class="pp">|</span> 164.259 <span class="pp">|</span> 153.018 to 175.501 <span class="pp">|</span></span>
<span id="cb16-132"><a href="#cb16-132" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Arm 1 <span class="pp">|</span> 166.211 <span class="pp">|</span> 154.886 to 177.535 <span class="pp">|</span></span>
<span id="cb16-133"><a href="#cb16-133" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Difference (arm 2 − arm 1) <span class="pp">|</span> -1.951 <span class="pp">|</span> -17.908 to 14.005; 0.811 <span class="pp">|</span></span>
<span id="cb16-134"><a href="#cb16-134" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Ratio (arm 2 / arm 1) <span class="pp">|</span> 0.988 <span class="pp">|</span> 0.897 to 1.088; 0.811 <span class="pp">|</span></span>
<span id="cb16-135"><a href="#cb16-135" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb16-136"><a href="#cb16-136" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-137"><a href="#cb16-137" aria-hidden="true" tabindex="-1"></a>At 180 days, RMST is 166 days in group 1 and 164 days in group 2, with no meaningful difference. To compare long-term effects, set a longer horizon such as 730 days. Group 1 has RMST 473 and group 2 has RMST 587; the difference and ratio have *p* values 0.035 and 0.042, respectively, so group 1 has shorter RMST through 730 days.</span>
<span id="cb16-138"><a href="#cb16-138" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-139"><a href="#cb16-139" aria-hidden="true" tabindex="-1"></a>::: {.callout-note appearance="simple" icon="false" title="Code 5.7"}</span>
<span id="cb16-140"><a href="#cb16-140" aria-hidden="true" tabindex="-1"></a><span class="in">```stata</span></span>
<span id="cb16-141"><a href="#cb16-141" aria-hidden="true" tabindex="-1"></a><span class="in">strmst2 g, tau(730)</span></span>
<span id="cb16-142"><a href="#cb16-142" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb16-143"><a href="#cb16-143" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb16-144"><a href="#cb16-144" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-145"><a href="#cb16-145" aria-hidden="true" tabindex="-1"></a>::: {.callout-note appearance="simple" icon="false" title="Code 5.7 output"}</span>
<span id="cb16-146"><a href="#cb16-146" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> RMST at 730 days <span class="pp">|</span> Estimate <span class="pp">|</span> 95% CI / p value <span class="pp">|</span></span>
<span id="cb16-147"><a href="#cb16-147" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span>:--<span class="pp">|</span>--:<span class="pp">|</span>:--<span class="pp">|</span></span>
<span id="cb16-148"><a href="#cb16-148" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Arm 2 <span class="pp">|</span> 586.704 <span class="pp">|</span> 523.148 to 650.260 <span class="pp">|</span></span>
<span id="cb16-149"><a href="#cb16-149" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Arm 1 <span class="pp">|</span> 473.868 <span class="pp">|</span> 391.176 to 556.561 <span class="pp">|</span></span>
<span id="cb16-150"><a href="#cb16-150" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Difference (arm 2 − arm 1) <span class="pp">|</span> 112.835 <span class="pp">|</span> 8.540 to 217.130; 0.034 <span class="pp">|</span></span>
<span id="cb16-151"><a href="#cb16-151" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Ratio (arm 2 / arm 1) <span class="pp">|</span> 1.238 <span class="pp">|</span> 1.008 to 1.520; 0.042 <span class="pp">|</span></span>
<span id="cb16-152"><a href="#cb16-152" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb16-153"><a href="#cb16-153" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-154"><a href="#cb16-154" aria-hidden="true" tabindex="-1"></a>An important drawback is that data collected after the cutoff are excluded, wasting data and reducing power. RMST is especially useful as an alternative to the hazard ratio under nonproportional hazards (Royston and Parmar 2013).</span>
<span id="cb16-155"><a href="#cb16-155" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-156"><a href="#cb16-156" aria-hidden="true" tabindex="-1"></a><span class="fu">### Landmark analysis</span></span>
<span id="cb16-157"><a href="#cb16-157" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-158"><a href="#cb16-158" aria-hidden="true" tabindex="-1"></a>Landmark analysis divides a Kaplan–Meier curve into periods and fits Cox models separately before and after a landmark. It recognizes that event-time distributions can differ between interventions. For surgery versus non-surgery, short-term complications may lower early survival after surgery, while later survival can be better. By choosing a landmark time and including only participants alive at that time for the later comparison, it avoids using information not yet available (Dafni 2011).</span>
<span id="cb16-159"><a href="#cb16-159" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-160"><a href="#cb16-160" aria-hidden="true" tabindex="-1"></a>In Case 5.1, choose 180 days from clinical knowledge. For the first 180 days, manually censor participants without an event at 180 days; the result shows no clear difference (*p*=0.373).</span>
<span id="cb16-161"><a href="#cb16-161" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-162"><a href="#cb16-162" aria-hidden="true" tabindex="-1"></a>::: {.callout-note appearance="simple" icon="false" title="Code 5.8"}</span>
<span id="cb16-163"><a href="#cb16-163" aria-hidden="true" tabindex="-1"></a><span class="in">```stata</span></span>
<span id="cb16-164"><a href="#cb16-164" aria-hidden="true" tabindex="-1"></a><span class="in">gen L1 = t1 if t1 &lt; 180</span></span>
<span id="cb16-165"><a href="#cb16-165" aria-hidden="true" tabindex="-1"></a><span class="in">replace L1 = 180 if t1 &gt;= 180</span></span>
<span id="cb16-166"><a href="#cb16-166" aria-hidden="true" tabindex="-1"></a><span class="in">gen deltaL1 = delta1 if t1 &lt; 180</span></span>
<span id="cb16-167"><a href="#cb16-167" aria-hidden="true" tabindex="-1"></a><span class="in">replace deltaL1 = 0 if t1 &gt;= 180</span></span>
<span id="cb16-168"><a href="#cb16-168" aria-hidden="true" tabindex="-1"></a><span class="in">stset L1, failure(deltaL1==1)</span></span>
<span id="cb16-169"><a href="#cb16-169" aria-hidden="true" tabindex="-1"></a><span class="in">stcox g</span></span>
<span id="cb16-170"><a href="#cb16-170" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb16-171"><a href="#cb16-171" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb16-172"><a href="#cb16-172" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-173"><a href="#cb16-173" aria-hidden="true" tabindex="-1"></a>::: {.callout-note appearance="simple" icon="false" title="Code 5.8 output"}</span>
<span id="cb16-174"><a href="#cb16-174" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Cox regression through 180 days <span class="pp">|</span> Value <span class="pp">|</span></span>
<span id="cb16-175"><a href="#cb16-175" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span>:--<span class="pp">|</span>--:<span class="pp">|</span></span>
<span id="cb16-176"><a href="#cb16-176" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Subjects / failures <span class="pp">|</span> 92 / 15 <span class="pp">|</span></span>
<span id="cb16-177"><a href="#cb16-177" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> HR for <span class="in">`g`</span> (95% CI) <span class="pp">|</span> 0.630 (0.229 to 1.739) <span class="pp">|</span></span>
<span id="cb16-178"><a href="#cb16-178" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> p value <span class="pp">|</span> 0.373 <span class="pp">|</span></span>
<span id="cb16-179"><a href="#cb16-179" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb16-180"><a href="#cb16-180" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-181"><a href="#cb16-181" aria-hidden="true" tabindex="-1"></a>For time after 180 days, remove participants whose survival time is shorter than 180 days and restart follow-up at 180 days. Acute lymphoblastic leukemia then has lower survival than low-risk AML.</span>
<span id="cb16-182"><a href="#cb16-182" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-183"><a href="#cb16-183" aria-hidden="true" tabindex="-1"></a>::: {.callout-note appearance="simple" icon="false" title="Code 5.9"}</span>
<span id="cb16-184"><a href="#cb16-184" aria-hidden="true" tabindex="-1"></a><span class="in">```stata</span></span>
<span id="cb16-185"><a href="#cb16-185" aria-hidden="true" tabindex="-1"></a><span class="in">gen L2 = t1 - 180</span></span>
<span id="cb16-186"><a href="#cb16-186" aria-hidden="true" tabindex="-1"></a><span class="in">stset L2, failure(delta1==1)</span></span>
<span id="cb16-187"><a href="#cb16-187" aria-hidden="true" tabindex="-1"></a><span class="in">stcox g if L2 &gt; 0</span></span>
<span id="cb16-188"><a href="#cb16-188" aria-hidden="true" tabindex="-1"></a><span class="in">sts graph if L2 &gt; 0, by(g) risktable censored(single)</span></span>
<span id="cb16-189"><a href="#cb16-189" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb16-190"><a href="#cb16-190" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb16-191"><a href="#cb16-191" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-192"><a href="#cb16-192" aria-hidden="true" tabindex="-1"></a>::: {.callout-note appearance="simple" icon="false" title="Code 5.9 output"}</span>
<span id="cb16-193"><a href="#cb16-193" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Cox regression after 180 days <span class="pp">|</span> Value <span class="pp">|</span></span>
<span id="cb16-194"><a href="#cb16-194" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span>:--<span class="pp">|</span>--:<span class="pp">|</span></span>
<span id="cb16-195"><a href="#cb16-195" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Subjects / failures <span class="pp">|</span> 77 / 31 <span class="pp">|</span></span>
<span id="cb16-196"><a href="#cb16-196" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> HR for <span class="in">`g`</span> (95% CI) <span class="pp">|</span> 0.466 (0.228 to 0.956) <span class="pp">|</span></span>
<span id="cb16-197"><a href="#cb16-197" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> p value <span class="pp">|</span> 0.037 <span class="pp">|</span></span>
<span id="cb16-198"><a href="#cb16-198" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb16-199"><a href="#cb16-199" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-200"><a href="#cb16-200" aria-hidden="true" tabindex="-1"></a>::: {.text-center}</span>
<span id="cb16-201"><a href="#cb16-201" aria-hidden="true" tabindex="-1"></a><span class="al">![](images/ch5-image6.png)</span>{width="100%"}</span>
<span id="cb16-202"><a href="#cb16-202" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-203"><a href="#cb16-203" aria-hidden="true" tabindex="-1"></a>Code 5.9 output: Kaplan–Meier curves after 180 days.</span>
<span id="cb16-204"><a href="#cb16-204" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb16-205"><a href="#cb16-205" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-206"><a href="#cb16-206" aria-hidden="true" tabindex="-1"></a>PH Cox analysis assumes equal hazard ratios at all time points. RMST compares areas under curves before a specified cutoff; landmark analysis compares survival before and after a specified landmark (Figure 5.2).</span>
<span id="cb16-207"><a href="#cb16-207" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-208"><a href="#cb16-208" aria-hidden="true" tabindex="-1"></a>::: {.text-center}</span>
<span id="cb16-209"><a href="#cb16-209" aria-hidden="true" tabindex="-1"></a><span class="al">![](images/ch5-image7.png)</span>{width="100%"}</span>
<span id="cb16-210"><a href="#cb16-210" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-211"><a href="#cb16-211" aria-hidden="true" tabindex="-1"></a>Figure 5.2 Alternatives to the Cox model in survival analysis.</span>
<span id="cb16-212"><a href="#cb16-212" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb16-213"><a href="#cb16-213" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-214"><a href="#cb16-214" aria-hidden="true" tabindex="-1"></a>Post hoc assessment of PH can be informative, but formal PH tests can miss clinically important deviations in small studies and flag clinically trivial deviations in large studies. Graphical displays, including Kaplan–Meier and Schoenfeld-residual plots, are often more useful. Piecewise hazard models can be used when PH fails, but post hoc selection of intervals can exaggerate time variation and late-period hazard ratios include only survivors, so they are no longer genuinely randomized comparisons. Nonproportionality may also result from clinically distinct subgroups, when subgroup analyses or stratified Cox models may help, or from nonadherence and crossover, which make treatment groups more similar over time. This is especially problematic in noninferiority trials because dilution can falsely support noninferiority. Per-protocol methods that adjust for nonadherence and crossover, estimating the average causal effect among adherers, may help recover the treatment effect. A hazard-ratio noninferiority margin can be inappropriate or hard to interpret when PH clearly fails.</span>
<span id="cb16-215"><a href="#cb16-215" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-216"><a href="#cb16-216" aria-hidden="true" tabindex="-1"></a><span class="fu">## Cox regression with time-dependent covariates</span></span>
<span id="cb16-217"><a href="#cb16-217" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-218"><a href="#cb16-218" aria-hidden="true" tabindex="-1"></a>Ordinary Cox regression studies baseline variables, but many covariates change over time. Smoking status can change as a person quits and resumes; C-reactive protein (CRP) changes with clinical status in sepsis. RMST and landmark analysis are unsuitable when the exposure is time varying, when no clear cutoff or landmark exists, or when a landmark would exclude many participants.</span>
<span id="cb16-219"><a href="#cb16-219" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-220"><a href="#cb16-220" aria-hidden="true" tabindex="-1"></a>**Case 5.2** considers CRP and death or serious complications in 100 patients with sepsis. <span class="in">`id`</span> identifies participants; <span class="in">`status`</span> is the composite outcome; <span class="in">`start`</span> and <span class="in">`stop`</span> are time in hours; <span class="in">`age`</span> is age. A second data table contains CRP by <span class="in">`id`</span>, measurement <span class="in">`time`</span>, and <span class="in">`crp`</span>. Before analysis, restructure data so that each row represents one period during which the time-varying covariate is constant. Patient 1 has only one CRP value during follow-up and needs one row. Patient 2 has several measurements and therefore several records: each record starts at one CRP measurement and stops at the next; the final record runs from the final pre-event measurement to the event time. This creates <span class="in">`tstart`</span>, <span class="in">`tstop`</span>, <span class="in">`endpt`</span>, and <span class="in">`crp`</span> variables.</span>
<span id="cb16-221"><a href="#cb16-221" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-222"><a href="#cb16-222" aria-hidden="true" tabindex="-1"></a>In the restructured data, repeated records from each participant require clustering by participant. The Cox *p* value is 0.040, indicating an association between CRP and the composite of death or serious complications.</span>
<span id="cb16-223"><a href="#cb16-223" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-224"><a href="#cb16-224" aria-hidden="true" tabindex="-1"></a>::: {.callout-note appearance="simple" icon="false" title="Code 5.10"}</span>
<span id="cb16-225"><a href="#cb16-225" aria-hidden="true" tabindex="-1"></a><span class="in">```stata</span></span>
<span id="cb16-226"><a href="#cb16-226" aria-hidden="true" tabindex="-1"></a><span class="in">gen time = tstop - tstart</span></span>
<span id="cb16-227"><a href="#cb16-227" aria-hidden="true" tabindex="-1"></a><span class="in">stset time, failure(endpt == 1)</span></span>
<span id="cb16-228"><a href="#cb16-228" aria-hidden="true" tabindex="-1"></a><span class="in">stcox crp, cluster(id)</span></span>
<span id="cb16-229"><a href="#cb16-229" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb16-230"><a href="#cb16-230" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb16-231"><a href="#cb16-231" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-232"><a href="#cb16-232" aria-hidden="true" tabindex="-1"></a>::: {.callout-note appearance="simple" icon="false" title="Code 5.10 output"}</span>
<span id="cb16-233"><a href="#cb16-233" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Clustered Cox regression <span class="pp">|</span> Value <span class="pp">|</span></span>
<span id="cb16-234"><a href="#cb16-234" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span>:--<span class="pp">|</span>--:<span class="pp">|</span></span>
<span id="cb16-235"><a href="#cb16-235" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Records / failures <span class="pp">|</span> 365 / 67 <span class="pp">|</span></span>
<span id="cb16-236"><a href="#cb16-236" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> HR for CRP (95% CI) <span class="pp">|</span> 0.9943 (0.9888 to 0.9997) <span class="pp">|</span></span>
<span id="cb16-237"><a href="#cb16-237" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> p value <span class="pp">|</span> 0.040 <span class="pp">|</span></span>
<span id="cb16-238"><a href="#cb16-238" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb16-239"><a href="#cb16-239" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-240"><a href="#cb16-240" aria-hidden="true" tabindex="-1"></a><span class="fu">## Competing-risk models</span></span>
<span id="cb16-241"><a href="#cb16-241" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-242"><a href="#cb16-242" aria-hidden="true" tabindex="-1"></a>Conventional survival outcomes are often binary—death/non-death or recurrence/non-recurrence. In practice there may be multiple endpoints, some of which prevent the event of interest or alter its probability; these are competing risks. For stroke risk in diabetes, death prevents observation of stroke and is a competing risk. A simple solution is to use a composite endpoint such as stroke or death. When the risks of different events must be distinguished, use cumulative incidence functions, Fine–Gray subdistribution hazards, or cause-specific hazards (Fine and Gray 1999; Putter et al. 2007; Austin et al. 2016).</span>
<span id="cb16-243"><a href="#cb16-243" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-244"><a href="#cb16-244" aria-hidden="true" tabindex="-1"></a>::: {.text-center}</span>
<span id="cb16-245"><a href="#cb16-245" aria-hidden="true" tabindex="-1"></a><span class="al">![](images/ch5-image8.png)</span>{width="100%"}</span>
<span id="cb16-246"><a href="#cb16-246" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-247"><a href="#cb16-247" aria-hidden="true" tabindex="-1"></a>Figure 5.3 Competing-risk events.</span>
<span id="cb16-248"><a href="#cb16-248" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb16-249"><a href="#cb16-249" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-250"><a href="#cb16-250" aria-hidden="true" tabindex="-1"></a>**Case 5.3** includes 205 participants with melanoma. <span class="in">`time`</span> is time after surgery; <span class="in">`status=1`</span> is death from melanoma, <span class="in">`status=2`</span> is censoring, and <span class="in">`status=3`</span> is death from other causes. Death from melanoma and death from other causes compete because either prevents the other.</span>
<span id="cb16-251"><a href="#cb16-251" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-252"><a href="#cb16-252" aria-hidden="true" tabindex="-1"></a><span class="fu">### Cumulative incidence function</span></span>
<span id="cb16-253"><a href="#cb16-253" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-254"><a href="#cb16-254" aria-hidden="true" tabindex="-1"></a>The cumulative incidence function (CIF) depicts the time-varying occurrence of the event of interest while accounting for competing events. It is nonparametric and replaces ordinary survival curves in this setting. Events are mutually exclusive, and the sum of cause-specific cumulative incidences equals the cumulative incidence of the composite event.</span>
<span id="cb16-255"><a href="#cb16-255" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-256"><a href="#cb16-256" aria-hidden="true" tabindex="-1"></a>::: {.callout-note appearance="simple" icon="false" title="Code 5.11"}</span>
<span id="cb16-257"><a href="#cb16-257" aria-hidden="true" tabindex="-1"></a><span class="in">```stata</span></span>
<span id="cb16-258"><a href="#cb16-258" aria-hidden="true" tabindex="-1"></a><span class="in">stset time, fail(status==1)</span></span>
<span id="cb16-259"><a href="#cb16-259" aria-hidden="true" tabindex="-1"></a><span class="in">stcurve, cif</span></span>
<span id="cb16-260"><a href="#cb16-260" aria-hidden="true" tabindex="-1"></a><span class="in">stset time, fail(status==3)</span></span>
<span id="cb16-261"><a href="#cb16-261" aria-hidden="true" tabindex="-1"></a><span class="in">stcurve, cif</span></span>
<span id="cb16-262"><a href="#cb16-262" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb16-263"><a href="#cb16-263" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb16-264"><a href="#cb16-264" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-265"><a href="#cb16-265" aria-hidden="true" tabindex="-1"></a>::: {.text-center}</span>
<span id="cb16-266"><a href="#cb16-266" aria-hidden="true" tabindex="-1"></a><span class="al">![](images/ch5-image9.png)</span>{width="100%"}</span>
<span id="cb16-267"><a href="#cb16-267" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-268"><a href="#cb16-268" aria-hidden="true" tabindex="-1"></a>Code 5.11 output: cumulative-incidence curves for competing events.</span>
<span id="cb16-269"><a href="#cb16-269" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb16-270"><a href="#cb16-270" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-271"><a href="#cb16-271" aria-hidden="true" tabindex="-1"></a><span class="fu">### Fine–Gray model</span></span>
<span id="cb16-272"><a href="#cb16-272" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-273"><a href="#cb16-273" aria-hidden="true" tabindex="-1"></a>The Fine–Gray model is a semiparametric proportional-hazards model for the time-varying rate of the event of interest among people who have not experienced it. It tests associations between that event and covariates; its coefficient, SHR, is a subdistribution hazard ratio. For melanoma death, compare participants with and without ulceration using <span class="in">`stcrreg`</span>. The result is strongly different (*p* &lt; 0.001); by contrast, death from other causes does not differ by ulceration.</span>
<span id="cb16-274"><a href="#cb16-274" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-275"><a href="#cb16-275" aria-hidden="true" tabindex="-1"></a>::: {.callout-note appearance="simple" icon="false" title="Code 5.12"}</span>
<span id="cb16-276"><a href="#cb16-276" aria-hidden="true" tabindex="-1"></a><span class="in">```stata</span></span>
<span id="cb16-277"><a href="#cb16-277" aria-hidden="true" tabindex="-1"></a><span class="in">stset time, fail(status == 1)</span></span>
<span id="cb16-278"><a href="#cb16-278" aria-hidden="true" tabindex="-1"></a><span class="in">stcrreg ulcer, compete(status == 3)</span></span>
<span id="cb16-279"><a href="#cb16-279" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb16-280"><a href="#cb16-280" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb16-281"><a href="#cb16-281" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-282"><a href="#cb16-282" aria-hidden="true" tabindex="-1"></a>::: {.callout-note appearance="simple" icon="false" title="Code 5.12 output"}</span>
<span id="cb16-283"><a href="#cb16-283" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Fine–Gray model: melanoma death <span class="pp">|</span> Value <span class="pp">|</span></span>
<span id="cb16-284"><a href="#cb16-284" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span>:--<span class="pp">|</span>--:<span class="pp">|</span></span>
<span id="cb16-285"><a href="#cb16-285" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Participants / melanoma deaths / competing deaths <span class="pp">|</span> 205 / 57 / 14 <span class="pp">|</span></span>
<span id="cb16-286"><a href="#cb16-286" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> SHR for ulceration (95% CI) <span class="pp">|</span> 4.111 (2.333 to 7.246) <span class="pp">|</span></span>
<span id="cb16-287"><a href="#cb16-287" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> p value <span class="pp">|</span> &lt;0.001 <span class="pp">|</span></span>
<span id="cb16-288"><a href="#cb16-288" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb16-289"><a href="#cb16-289" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-290"><a href="#cb16-290" aria-hidden="true" tabindex="-1"></a>::: {.callout-note appearance="simple" icon="false" title="Code 5.13"}</span>
<span id="cb16-291"><a href="#cb16-291" aria-hidden="true" tabindex="-1"></a><span class="in">```stata</span></span>
<span id="cb16-292"><a href="#cb16-292" aria-hidden="true" tabindex="-1"></a><span class="in">stset time, fail(status == 3)</span></span>
<span id="cb16-293"><a href="#cb16-293" aria-hidden="true" tabindex="-1"></a><span class="in">stcrreg ulcer, compete(status == 1)</span></span>
<span id="cb16-294"><a href="#cb16-294" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb16-295"><a href="#cb16-295" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb16-296"><a href="#cb16-296" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-297"><a href="#cb16-297" aria-hidden="true" tabindex="-1"></a>::: {.callout-note appearance="simple" icon="false" title="Code 5.13 output"}</span>
<span id="cb16-298"><a href="#cb16-298" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Fine–Gray model: other-cause death <span class="pp">|</span> Value <span class="pp">|</span></span>
<span id="cb16-299"><a href="#cb16-299" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span>:--<span class="pp">|</span>--:<span class="pp">|</span></span>
<span id="cb16-300"><a href="#cb16-300" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> SHR for ulceration (95% CI) <span class="pp">|</span> 1.255 (0.438 to 3.599) <span class="pp">|</span></span>
<span id="cb16-301"><a href="#cb16-301" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> p value <span class="pp">|</span> 0.673 <span class="pp">|</span></span>
<span id="cb16-302"><a href="#cb16-302" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb16-303"><a href="#cb16-303" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-304"><a href="#cb16-304" aria-hidden="true" tabindex="-1"></a>The corresponding CIF curves show higher melanoma-death cumulative incidence with ulceration and no clear difference in other-cause death.</span>
<span id="cb16-305"><a href="#cb16-305" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-306"><a href="#cb16-306" aria-hidden="true" tabindex="-1"></a>::: {.callout-note appearance="simple" icon="false" title="Code 5.14"}</span>
<span id="cb16-307"><a href="#cb16-307" aria-hidden="true" tabindex="-1"></a><span class="in">```stata</span></span>
<span id="cb16-308"><a href="#cb16-308" aria-hidden="true" tabindex="-1"></a><span class="in">stset time, fail(status==1)</span></span>
<span id="cb16-309"><a href="#cb16-309" aria-hidden="true" tabindex="-1"></a><span class="in">stcrreg ulcer, compete(status==3)</span></span>
<span id="cb16-310"><a href="#cb16-310" aria-hidden="true" tabindex="-1"></a><span class="in">stcurve, cif at1(ulcer=0) at2(ulcer=1)</span></span>
<span id="cb16-311"><a href="#cb16-311" aria-hidden="true" tabindex="-1"></a><span class="in">stset time, fail(status==3)</span></span>
<span id="cb16-312"><a href="#cb16-312" aria-hidden="true" tabindex="-1"></a><span class="in">stcrreg ulcer, compete(status==1)</span></span>
<span id="cb16-313"><a href="#cb16-313" aria-hidden="true" tabindex="-1"></a><span class="in">stcurve, cif at1(ulcer=0) at2(ulcer=1)</span></span>
<span id="cb16-314"><a href="#cb16-314" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb16-315"><a href="#cb16-315" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb16-316"><a href="#cb16-316" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-317"><a href="#cb16-317" aria-hidden="true" tabindex="-1"></a>::: {.text-center}</span>
<span id="cb16-318"><a href="#cb16-318" aria-hidden="true" tabindex="-1"></a><span class="al">![](images/ch5-image10.png)</span>{width="100%"}</span>
<span id="cb16-319"><a href="#cb16-319" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-320"><a href="#cb16-320" aria-hidden="true" tabindex="-1"></a>Code 5.14 output: group-specific cumulative-incidence curves.</span>
<span id="cb16-321"><a href="#cb16-321" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb16-322"><a href="#cb16-322" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-323"><a href="#cb16-323" aria-hidden="true" tabindex="-1"></a><span class="fu">### Cause-specific hazard model</span></span>
<span id="cb16-324"><a href="#cb16-324" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-325"><a href="#cb16-325" aria-hidden="true" tabindex="-1"></a>A simpler competing-risk analysis is the cause-specific hazard model: treat events not of interest as artificially censored and fit a Cox model in the resulting data. The result agrees with Fine–Gray: melanoma-death risk differs by ulceration, with *p* &lt; 0.001.</span>
<span id="cb16-326"><a href="#cb16-326" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-327"><a href="#cb16-327" aria-hidden="true" tabindex="-1"></a>::: {.callout-note appearance="simple" icon="false" title="Code 5.15"}</span>
<span id="cb16-328"><a href="#cb16-328" aria-hidden="true" tabindex="-1"></a><span class="in">```stata</span></span>
<span id="cb16-329"><a href="#cb16-329" aria-hidden="true" tabindex="-1"></a><span class="in">generate status_cause = 2</span></span>
<span id="cb16-330"><a href="#cb16-330" aria-hidden="true" tabindex="-1"></a><span class="in">replace status_cause = 1 if status == 1</span></span>
<span id="cb16-331"><a href="#cb16-331" aria-hidden="true" tabindex="-1"></a><span class="in">stset time, fail(status_cause==1)</span></span>
<span id="cb16-332"><a href="#cb16-332" aria-hidden="true" tabindex="-1"></a><span class="in">stcox ulcer</span></span>
<span id="cb16-333"><a href="#cb16-333" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb16-334"><a href="#cb16-334" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb16-335"><a href="#cb16-335" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-336"><a href="#cb16-336" aria-hidden="true" tabindex="-1"></a>::: {.callout-note appearance="simple" icon="false" title="Code 5.15 output"}</span>
<span id="cb16-337"><a href="#cb16-337" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Cause-specific Cox model <span class="pp">|</span> Value <span class="pp">|</span></span>
<span id="cb16-338"><a href="#cb16-338" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span>:--<span class="pp">|</span>--:<span class="pp">|</span></span>
<span id="cb16-339"><a href="#cb16-339" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Participants / melanoma deaths <span class="pp">|</span> 205 / 57 <span class="pp">|</span></span>
<span id="cb16-340"><a href="#cb16-340" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> HR for ulceration (95% CI) <span class="pp">|</span> 4.357 (2.442 to 7.773) <span class="pp">|</span></span>
<span id="cb16-341"><a href="#cb16-341" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> p value <span class="pp">|</span> &lt;0.001 <span class="pp">|</span></span>
<span id="cb16-342"><a href="#cb16-342" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb16-343"><a href="#cb16-343" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-344"><a href="#cb16-344" aria-hidden="true" tabindex="-1"></a><span class="fu">## Limitations of the hazard ratio</span></span>
<span id="cb16-345"><a href="#cb16-345" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-346"><a href="#cb16-346" aria-hidden="true" tabindex="-1"></a>Three common summaries of survival outcomes are the hazard ratio (HR), median survival in each treatment group, and time-point survival such as 1-year progression-free or overall survival. HR uses information from the whole survival curve and summarizes relative treatment effect over follow-up; median survival uses one point of each curve, and a time-point survival probability is also limited. HR can be unadjusted (a univariable Cox model) or adjusted (a multivariable Cox model incorporating confounders such as age, sex, stage, and performance status). Medians and time-point probabilities derived from curves are usually unadjusted.</span>
<span id="cb16-347"><a href="#cb16-347" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-348"><a href="#cb16-348" aria-hidden="true" tabindex="-1"></a>HR has important limitations. First, if curves substantially violate PH, an overall HR is hard to interpret because it changes markedly over time, and PH tests can have low power. Second, censoring can create selection bias if it is related to both intervention and outcome. Third, HR changes with the follow-up period—the values at 180 and 730 days in Case 5.1 differ—so a reported HR is an average. Fourth, HR is relative: statistical significance need not imply clinical importance. Clinicians should consider absolute measures with coherent clinical meaning, including time-point survival and median survival. Across tumors, HR=0.75 might mean a 50-day median-survival benefit or only about 10 days.</span>
<span id="cb16-349"><a href="#cb16-349" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-350"><a href="#cb16-350" aria-hidden="true" tabindex="-1"></a>Finally, extending an HR beyond observed follow-up requires great caution. Without later information, continued PH cannot be assumed; subsequent or palliative therapies can markedly affect survival. Because the risk set changes as people die, later HRs may carry intrinsic selection bias even in randomized trials—“the hazards of hazard ratios” (Hernán 2010). Interpret HR together with survival curves, RMST, and absolute risk at specified times.</span>
<span id="cb16-351"><a href="#cb16-351" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-352"><a href="#cb16-352" aria-hidden="true" tabindex="-1"></a><span class="fu">## References {.unnumbered}</span></span>
<span id="cb16-353"><a href="#cb16-353" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-354"><a href="#cb16-354" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>Zhang Z, Reinikainen J, Adeleke KA, Pieterse ME, Groothuis-Oudshoorn CGM. Time-varying covariates and coefficients in Cox regression models. *Ann Transl Med*. 2018;6(7):121.</span>
<span id="cb16-355"><a href="#cb16-355" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>Gregson J, Sharples L, Stone GW, Burman CF, Öhrn F, Pocock S. Nonproportional hazards for time-to-event outcomes in clinical trials. *J Am Coll Cardiol*. 2019;74(16):2102-2112.</span>
<span id="cb16-356"><a href="#cb16-356" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>Cox DR. Regression models and life-tables. *Journal of the Royal Statistical Society: Series B*. 1972;34(2):187-220.</span>
<span id="cb16-357"><a href="#cb16-357" aria-hidden="true" tabindex="-1"></a><span class="ss">4. </span>Kaplan EL, Meier P. Nonparametric estimation from incomplete observations. *JASA*. 1958;53(282):457-481.</span>
<span id="cb16-358"><a href="#cb16-358" aria-hidden="true" tabindex="-1"></a><span class="ss">5. </span>Fine JP, Gray RJ. A proportional hazards model for the subdistribution of a competing risk. *JASA*. 1999;94(446):496-509.</span>
<span id="cb16-359"><a href="#cb16-359" aria-hidden="true" tabindex="-1"></a><span class="ss">6. </span>Putter H, Fiocco M, Geskus RB. Competing risks and multi-state models. *Statistics in Medicine*. 2007;26(11):2389-2430.</span>
<span id="cb16-360"><a href="#cb16-360" aria-hidden="true" tabindex="-1"></a><span class="ss">7. </span>Austin PC, Lee DS, Fine JP. Analysis of survival data in the presence of competing risks. *Circulation*. 2016;133(6):601-609.</span>
<span id="cb16-361"><a href="#cb16-361" aria-hidden="true" tabindex="-1"></a><span class="ss">8. </span>Royston P, Parmar MK. Restricted mean survival time. *BMC Medical Research Methodology*. 2013;13:152.</span>
<span id="cb16-362"><a href="#cb16-362" aria-hidden="true" tabindex="-1"></a><span class="ss">9. </span>Dafni U. Landmark analysis at the 25-year landmark point. *Circulation: Cardiovascular Quality and Outcomes*. 2011;4(3):363-371.</span>
<span id="cb16-363"><a href="#cb16-363" aria-hidden="true" tabindex="-1"></a><span class="ss">10. </span>Hernán MA. The hazards of hazard ratios. *Epidemiology*. 2010;21(1):13-15.</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></div>
</div></div></div></div></div>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p>© 2026 Nidan Qiao · Released under CC BY 4.0</p>
</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>